name: Déploiement vers AlwaysData

on:
  push:
    branches:
      - main

jobs:
  Connexion:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH avec le serveur AlwaysData
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd $HOME/www/
            echo "✅ Connexion réussie depuis GitHub Actions !"
